services:
  postgres:
    image: postgres:16-alpine
    container_name: mobile-store-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mobile_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - mobile_store_pgdata:/var/lib/postgresql/data

volumes:
  mobile_store_pgdata:
